[
 [:create_vector[:s :..]    "create a vector with the given scalars as elements"]
 [:create_matrix[:v :..]    "create a matrix with the given vectors as rows"]
 [:fill_vector [:d :fillnumber]        "create a vector of a given size that is filled with the given number"]
 [:fill_matrix [:d0 :d1 :fillnumber]   "create a vector of a given size that is filled with the given number"]
 [:create_unity_matrix [:d]                "create a unity matrix of a give size"]
 [:add_columns_to_matrix [:A :B]         "Add a matrix to the left of another matrix"]
 [:add_rows_to_matrix [:A :B]            "Add a matrix to the bottom of another matrix"]
 [:insert_rows_in_matrix [:A :B :index]  "Insert a matrix into another matrix at the given row index"]
 [:insert_columns_in_matrix [:A :B :index] "Insert a matrix into another matrix at the given column index"]
 [:replace_rows_in_matrix [:A :B :index] "replace a part of matrix with another matrix at the given row index"]
 [:remove_columns_in_matrix [:A :B :index] "replace a part of matrix with another matrix at the given column index"]
 [:vector_to_row_matrix [:v] "Convert a vector to a row matrix"]
 [:vector_to_column_matrix [:v] "Convert a vector to a column matrix"]]
